public with sharing class AA_InteractionContext {
	public AA_InteractionContext() {
	}
	public String interaction_id;
	public String interaction_id_type;
	public String token;
	public String user_network_id;
	public String user_email;
	public String user_id;
	public String salesforce_user_id;
	public String network_id;
	public String enterprise_id;
	public String enterprise_name;
	public String client_id;
}
